#!/usr/bin/env python3
"""Round 4 of the v4.26 sky-and-water concepts: soft clouds and a new, smaller bird. The dolphin
and the sailboat stay as concept B "Rilievo" delivered them.

Run from ``tools/assets`` with the pinned venv:

    /home/bober/.venvs/paperscrape-assets/bin/python concepts/skywater/build_skywater_round4.py

Two combinations, paired for capture economy only:

    batuffolo_colomba   cloud C1 "Batuffolo" (edge feathered 1.5 units) + bird A "Colomba"
    vapore_gabbiano     cloud C2 "Vapore"    (edge feathered 3 units)   + bird B "Gabbiano morbido"

**No cut edges and no second sheet.** The cloud is one mass of four large round lobes that meet
in shallow, rounded joints -- no cusps, no notches -- over a wide low lobe that gives it a soft,
nearly flat base. Its tone is a *gradient inside the one shape*: one vertical ramp from white
at the crown to a light grey at the base, shared by all the lobes so nothing reads as a seam or a
second paper. The silhouette is then feathered by a Gaussian blur of the whole mass, so the edge
is a passage of alpha rather than a line. Everything is drawn from primitives here; nothing is
traced or sampled from anywhere.

**The bird is compact.** Both variants are ~48 px across (1.3 person heights), with the body on
the flap axis and the wings rising above it as two soft, rounded shapes rather than two blades:
A "Colomba" has a plump body, a fan tail and two leaf-shaped wings raised together; B "Gabbiano
morbido" has a slimmer body and longer rounded wings in a shallow V. Both carry the same soft
gradient (white above, light grey below) and a light feather of the edge.

**Tint-class budget** (`SpriteTintClassTest`: mean of every pixel with alpha > 0 at least 220,
r = g = b everywhere): the ramps end at #DEDEDE (13 % below white) and the script prints the
mean and the minimum for every sprite. Low-alpha pixels left at 0 by the blur's unpremultiply
are set back to white so nothing in the mask is darker than the ramp.

Canvases: cloud 798x396 (unchanged); bird 51x21 px, CANVAS_PIXELS, flap axis at row 15 --
``BIRD_SPRITE_ORIGIN_X/Y_PX`` become (-25, -15) in the capture build.
"""
from __future__ import annotations

import io
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent.parent))

from build_skywater_concepts import UNIT, Sprite, emit_svg, dolphin, hull, sail, CLOUD_W, CLOUD_H, NOTES  # noqa: E402
from paperscrape_assets import raster  # noqa: E402
from paperscrape_assets.inventory import measure_raster  # noqa: E402

RAMP_BOTTOM = "#DEDEDE"

# ------------------------------------------------------------------------------ the cloud
#: four lobes (cx, cy, r) in units on the 266x132 canvas, deep overlaps so the joints are shallow,
#: and a wide low lobe for the base.
CLOUD_LOBES = [(62, 82, 42), (124, 58, 56), (190, 74, 48), (238, 98, 30), (30, 104, 26)]
CLOUD_BASE = (134, 108, 118, 22)   # cx, cy, rx, ry


def cloud_svg(blur_units: float, ramp_top_y: float = 24.0, ramp_bottom_y: float = 128.0) -> str:
    w, h = CLOUD_W * UNIT, CLOUD_H * UNIT
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:g}" height="{h:g}" viewBox="0 0 {CLOUD_W:g} {CLOUD_H:g}">',
             "<!-- v4.26 round-4 soft cloud: one mass of round lobes, one vertical ramp, one feathered edge. "
             "Generated by tools/assets/concepts/skywater/build_skywater_round4.py from primitives only. -->",
             "<defs>",
             f'<linearGradient id="ramp" gradientUnits="userSpaceOnUse" x1="0" y1="{ramp_top_y:g}" x2="0" y2="{ramp_bottom_y:g}">'
             f'<stop offset="0" stop-color="#FFFFFF"/><stop offset="0.45" stop-color="#F4F4F4"/><stop offset="1" stop-color="{RAMP_BOTTOM}"/></linearGradient>',
             f'<filter id="soft" x="-5%" y="-10%" width="110%" height="120%"><feGaussianBlur stdDeviation="{blur_units:g}"/></filter>',
             "</defs>",
             '<g filter="url(#soft)" fill="url(#ramp)">']
    cx, cy, rx, ry = CLOUD_BASE
    parts.append(f'<ellipse cx="{cx}" cy="{cy}" rx="{rx}" ry="{ry}"/>')
    for x, y, r in CLOUD_LOBES:
        parts.append(f'<circle cx="{x}" cy="{y}" r="{r}"/>')
    parts.append("</g></svg>")
    return "\n".join(parts)


# ------------------------------------------------------------------------------ the bird
BIRD_W, BIRD_H, BIRD_AXIS = 51, 21, 15


def bird_svg(style: str) -> str:
    """51x21 canvas pixels; the body sits on row 15 (the flap axis), the wings rise above it."""
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{BIRD_W}" height="{BIRD_H}" viewBox="0 0 {BIRD_W} {BIRD_H}">',
             f"<!-- v4.26 round-4 bird '{style}': soft compact bird, body on the flap axis (row {BIRD_AXIS}), "
             "wings above. Generated by tools/assets/concepts/skywater/build_skywater_round4.py from primitives only. -->",
             "<defs>",
             f'<linearGradient id="ramp" gradientUnits="userSpaceOnUse" x1="0" y1="1" x2="0" y2="{BIRD_H - 1}">'
             f'<stop offset="0" stop-color="#FFFFFF"/><stop offset="0.55" stop-color="#F6F6F6"/><stop offset="1" stop-color="{RAMP_BOTTOM}"/></linearGradient>',
             '<filter id="soft" x="-5%" y="-10%" width="110%" height="120%"><feGaussianBlur stdDeviation="0.45"/></filter>',
             "</defs>",
             '<g filter="url(#soft)" fill="url(#ramp)">']
    a = BIRD_AXIS
    if style == "colomba":
        # far wing (a tone back), body, near wing, tail, head
        parts.append(f'<path fill="#E9E9E9" d="M 22 {a - 2} C 20 {a - 8}, 24 {a - 13}, 30 {a - 14} C 31 {a - 9}, 28 {a - 4}, 24 {a - 1} Z"/>')
        parts.append(f'<path d="M 12 {a + 1} C 10 {a - 3}, 14 {a - 5}, 22 {a - 5} L 36 {a - 4} C 40 {a - 4}, 42 {a - 1}, 42 {a + 1} '
                     f'C 42 {a + 4}, 38 {a + 5}, 30 {a + 5} L 16 {a + 5} C 12 {a + 5}, 10 {a + 3}, 12 {a + 1} Z"/>')
        parts.append(f'<path d="M 4 {a - 2} L 13 {a - 3} L 14 {a + 4} L 4 {a + 3} Z"/>')  # tail fan
        parts.append(f'<path d="M 26 {a - 3} C 26 {a - 9}, 31 {a - 14}, 37 {a - 14} C 39 {a - 9}, 36 {a - 3}, 30 {a}  Z"/>')
        parts.append(f'<circle cx="43" cy="{a - 1}" r="3.6"/>')
        parts.append(f'<path d="M 46 {a - 1.5} L 49.5 {a - 0.8} L 46 {a + 0.5} Z"/>')  # beak
    else:
        # gabbiano morbido: slim body, long rounded wings in a shallow V, small head and tail
        parts.append(f'<path fill="#E9E9E9" d="M 22 {a - 2} C 16 {a - 5}, 9 {a - 8}, 3 {a - 8} C 5 {a - 5}, 12 {a - 2}, 22 {a + 1} Z"/>')
        parts.append(f'<path d="M 9 {a + 0.5} C 12 {a - 3}, 18 {a - 4}, 26 {a - 4} L 38 {a - 3} C 41 {a - 3}, 42 {a - 1}, 42 {a + 1} '
                     f'C 41 {a + 3.5}, 37 {a + 4.5}, 30 {a + 4.5} L 16 {a + 4} C 12 {a + 4}, 9 {a + 3}, 9 {a + 0.5} Z"/>')
        parts.append(f'<path d="M 24 {a - 2} C 30 {a - 7}, 38 {a - 11}, 47 {a - 12} C 45 {a - 8}, 38 {a - 4}, 30 {a}  Z"/>')
        parts.append(f'<circle cx="43.5" cy="{a - 1}" r="3.2"/>')
        parts.append(f'<path d="M 46.2 {a - 1.4} L 49.6 {a - 0.6} L 46.2 {a + 0.4} Z"/>')
        parts.append(f'<path d="M 3 {a - 1} L 10 {a - 2.5} L 10 {a + 3.5} L 3 {a + 2} Z"/>')
    parts.append("</g></svg>")
    return "\n".join(parts)


# ------------------------------------------------------------------------------ build
def clean_mask(png_bytes: bytes) -> tuple[bytes, float, int, float]:
    """Sets the colour of near-transparent pixels back to white (the blur's unpremultiply leaves
    them at 0) and returns (png, mean over alpha>0, min over alpha>0, share of partial alpha)."""
    im = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
    a = np.array(im)
    low = (a[..., 3] > 0) & (a[..., 3] < 24)
    a[low, 0:3] = 255
    op = a[..., 3] > 0
    mean = float(a[..., 0][op].mean())
    mn = int(a[..., 0][op].min())
    partial = float(((a[..., 3] > 0) & (a[..., 3] < 255)).sum() / op.sum())
    out = io.BytesIO()
    Image.fromarray(a, "RGBA").save(out, format="PNG", optimize=False, compress_level=9)
    return out.getvalue(), mean, mn, partial


COMBOS = {"batuffolo_colomba": (1.5, "colomba"), "vapore_gabbiano": (3.0, "gabbiano")}


def build(combo: str) -> None:
    blur, bird_style = COMBOS[combo]
    out = HERE / "round4" / combo / "svg"
    out.mkdir(parents=True, exist_ok=True)
    entries = []
    items = [("bird_body", bird_svg(bird_style), (BIRD_W, BIRD_H), "CANVAS_PIXELS", "TINTABLE", "animal"),
             ("cloud_body", cloud_svg(blur), (int(CLOUD_W * UNIT), int(CLOUD_H * UNIT)), "SCENE_UNITS", "TINTABLE", "sky")]
    for sprite in (dolphin("rilievo"), hull("rilievo"), sail("rilievo")):
        items.append((sprite.name, emit_svg(sprite, "rilievo"),
                      (int(sprite.width_units * UNIT), int(sprite.height_units * UNIT)), sprite.scale, sprite.tint, sprite.category))
    for name, svg, expected, scale, tint, category in items:
        (out / f"{name}.svg").write_text(svg + "\n", encoding="utf-8")
        r = raster.render_svg(svg)
        if r.size != expected:
            raise SystemExit(f"{name}: rendered {r.size}, expected {expected}")
        png = r.png_bytes
        stats = ""
        if tint == "TINTABLE":
            png, mean, mn, partial = clean_mask(png)
            stats = f" tint mean {mean:.1f} min {mn} partial-alpha {partial:.0%}"
        (out / f"{name}.png").write_bytes(png)
        m = measure_raster(name, raster.render_svg(svg))
        entries.append({"name": name, "category": category, "width": expected[0], "height": expected[1],
                        "contentBox": list(m.content_bbox), "scale": scale, "tint": tint, "usage": "concept",
                        "anchorRule": "PART_LOCAL", "anchor": [0, 0], "season": "all",
                        "source": {"kind": "svg", "file": f"{name}.svg"},
                        "notes": (f"Round-4 concept '{combo}'. " + (f"Flap axis row {BIRD_AXIS}, blit origin (-25, -15), {BIRD_W}x{BIRD_H} CANVAS_PIXELS." if name == "bird_body" else NOTES[name]))})
        print(f"  {combo:20s} {name:14s} {expected[0]}x{expected[1]} content {list(m.content_bbox)}{stats}")
    reg = {"schemaVersion": 2, "note": f"Registry of the v4.26 round-4 combination '{combo}'; these sprites are NOT shipped.", "sprites": entries}
    (HERE / "round4" / combo / "sprites.concept.json").write_text(json.dumps(reg, indent=1) + "\n", encoding="utf-8")


if __name__ == "__main__":
    for combo in (sys.argv[1:] or list(COMBOS)):
        build(combo)
