#!/usr/bin/env python3
"""v4.28 phase-2 concept: the walking adults with a *carrying* arm, in three poses.

Run from ``tools/assets`` with the pinned venv:

    /home/bober/.venvs/paperscrape-assets/bin/python concepts/people/build_carry_concepts.py

Concept B "Rilievo" as shipped (``build_people_concepts.walker_rilievo``, style ``rilievo_occhi``)
draws both arms as a straight limb from the shoulder to the hand that swings -5 / 0 / +5 units
across the three walk frames. This script draws the same figure with the **near arm bent** and a
handle in its hand, as a pose "carrying an object" that any object could hang from -- an umbrella
today, a bag or a suitcase tomorrow. The far arm keeps swinging. Children are not drawn: the
proposal is that only adults carry.

    pose 1 "alzato"    forearm raised, the hand at cheek height ahead of the face; fixed on all frames
    pose 2 "al petto"  forearm across the chest, the hand at chest height; fixed on all frames
    pose 3 "oscilla"   pose 1, but the elbow and the hand follow the walk swing by 0.6 of it

The canvas is the shipped one: the 41x85 authoring canvas trimmed by the same (1,1) offset to
39x84, so the shipped anchor (-19.5, -84) and every other walk frame stay co-registered. The
script checks that by re-rendering the shipped man's summer frames through the same path and
comparing them byte for byte with what ships. Skin tones come from the shipped
``tools/generate_skin_variants.py`` recolour, applied here to the rendered base.

Output: ``concepts/people/carry_concepts/<name>.svg|png`` (the shipped pose is P1 and is
regenerated by ``build_carry_sprites.py`` into ``carry/``; these three are the proposal record) (base + three tones), ``hands.json`` with the
hand centre and the point above the head an umbrella handle would reach of every pose and frame in trimmed sprite units (what the call
site needs to hang an object), and a size report.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TOOL_ROOT = HERE.parent.parent
REPO = TOOL_ROOT.parent.parent
sys.path.insert(0, str(TOOL_ROOT))
sys.path.insert(0, str(HERE))

import build_people_concepts as bpc  # noqa: E402
from build_people_concepts import Sprite, cut, oval, quad, shade, ground_shadow, ADULT, ADULT_TOP, CHILD_TOP, SUMMER, WINTER, SKIN, HAIR, CREAM, UNIT  # noqa: E402
from paperscrape_assets import raster  # noqa: E402
from paperscrape_assets.inventory import measure_raster  # noqa: E402

_spec = importlib.util.spec_from_file_location("skin", REPO / "tools" / "generate_skin_variants.py")
skin_tool = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(skin_tool)

STYLE = "rilievo_occhi"
HANDLE = "#5B4A3E"
TRIM = (1, 1)            # the shipped family's trim: 41x85 -> 39x84, origin +(1,1)
CANVAS = (39, 84)
POSES = {1: "alzato", 2: "petto", 3: "oscilla"}


def walker(kind: str, season: str, frame: int, pose: int | None) -> tuple[Sprite, dict]:
    """``walker_rilievo`` verbatim, except the near arm when ``pose`` is given. Returns the sprite
    and, for a carrying pose, the hand centre and the handle top in untrimmed units."""
    name = f"person_{kind}_{season}_walk{frame}" if pose is None else f"person_{kind}_{season}_carry{pose}{frame}"
    s = Sprite(name, 41, 85)
    seed = f"person_{kind}_{season}_walk{frame}"   # the same wobble as the shipped frame
    adult = ADULT[kind]
    top = ADULT_TOP if adult else CHILD_TOP
    gar = (SUMMER if season == "summer" else WINTER)[kind]
    skin, hair = SKIN[kind], HAIR[kind]
    cx = 20.0
    head_ry = 11.5 if adult else 9.5
    head_rx = 10.5 if adult else 9.0
    head_cy = top + head_ry + 1.5
    chin = head_cy + head_ry
    shoulder = chin + 2
    hip = 56 if adult else 62
    stride = (6.5, 0.0, -6.5)[frame]
    swing = (-5.0, 0.0, 5.0)[frame]
    bob = 1.0 if frame == 1 else 0.0
    ground_shadow(s, cx=cx, rx=13 if adult else 11)
    leg_w = 6.5 if adult else 5.5
    leg_col = gar["bottom"] or skin
    s.add(cut(quad(cx - 3, hip - 2, leg_w, cx - 3 - stride, 81 - bob, leg_w - 0.5), seed + "L1"), shade(leg_col, 0.14))
    s.add(cut(quad(cx + 3, hip - 2, leg_w, cx + 3 + stride, 81 - bob, leg_w - 0.5), seed + "L2"), leg_col)
    for i, fx in enumerate((cx - 3 - stride, cx + 3 + stride)):
        s.add(cut(oval(fx + 1, 81.5 - bob, 5.0, 2.6, 10), seed + f"F{i}", 0.25), gar["shoe"] if i else shade(gar["shoe"], 0.14))
    hem = hip + (8 if season == "winter" else (3 if kind in ("woman", "girl") else 0))
    sw = 11.5 if adult else 9.5
    hw = (14.5 if season == "summer" and kind in ("woman", "girl") else 10.0) if adult else (11.0 if kind == "girl" else 8.5)
    body = [(cx - sw + 2, shoulder), (cx + sw - 2, shoulder), (cx + sw, shoulder + 3), (cx + hw, hem - 2), (cx + hw - 2, hem), (cx - hw + 2, hem), (cx - hw, hem - 2), (cx - sw, shoulder + 3)]
    s.add(cut(body, seed + "B"), gar["top"])
    arm_len = 22 if adult else 16
    arm_w = 5.5 if adult else 4.5
    sleeve = gar["top"]
    hands = {}
    carry_parts = []
    for i, (ax, sw_dir, col) in enumerate(((cx - sw + 1.5, -swing, shade(sleeve, 0.16)), (cx + sw - 1.5, swing, sleeve))):
        if i == 1 and pose is not None:
            # ---- the carrying arm: upper arm to an elbow, forearm to a hand, a handle in it ----
            # The hand may not reach the canvas edge: hand radius 3.2 plus the under-paper's
            # 1.4 must stay inside 39 trimmed units, which bounds the forward reach at ~ax+3.
            follow = 0.4 * swing if pose == 3 else 0.0
            if pose == 2:
                elbow = (ax + 1.0, shoulder + 13.0)
                hand = (ax + 3.5, shoulder + 5.0)
            else:
                elbow = (ax + 3.0 + follow, shoulder + 11.0)
                hand = (ax + 2.5 + follow, chin - 3.0 + (0.4 * swing if pose == 3 else 0.0))
            # Drawn last (see the end): the hand is in front of the face, and the shipped order
            # puts the head over the arms.
            handle_top = (hand[0], top + 1.0)
            carry_parts = [
                (cut(quad(ax, shoulder + 2, arm_w, elbow[0], elbow[1], arm_w - 0.5), seed + "A1"), col, {}),
                (cut(quad(elbow[0], elbow[1], arm_w - 0.5, hand[0], hand[1], arm_w - 1.0), seed + "A1b"), col, {}),
                (cut(oval(hand[0], hand[1], 3.2, 3.2, 10), seed + "Hd1", 0.25), skin, {}),
            ]
            hands = {"hand": hand, "handle_top": handle_top}
            continue
        s.add(cut(quad(ax, shoulder + 2, arm_w, ax + sw_dir, shoulder + 2 + arm_len, arm_w - 0.5), seed + f"A{i}"), col)
        s.add(cut(oval(ax + sw_dir, shoulder + 3 + arm_len, 3.2, 3.2, 10), seed + f"Hd{i}", 0.25), skin if i else shade(skin, 0.14))
    if season == "winter":
        s.add(cut([(cx - 8.5, chin - 1.5), (cx + 8.5, chin - 1.5), (cx + 9, chin + 4.5), (cx + 3, chin + 12), (cx - 2, chin + 12), (cx - 2, chin + 5), (cx - 8.5, chin + 4.5)], seed + "scarf"), gar["belt"])
    s.add(cut([(cx - 3, chin - 3), (cx + 3.5, chin - 3), (cx + 3.5, shoulder + 2), (cx - 3, shoulder + 2)], seed + "N"), skin, relief=False)
    hx, hy = cx + 0.5, head_cy
    if season == "winter" and kind == "woman":
        s.add(cut(oval(hx - head_rx + 1, hy + 4, 4.5, 9.5, 10), seed + "hairw", 0.3), hair)
    if season == "winter" and kind == "boy":
        s.add(cut(oval(hx - 3, hy + 0.5, head_rx + 4.5, head_ry + 4.5, 14), seed + "hood", 0.3), gar["top"])
        s.add(cut(oval(hx - 1.5, hy + 0.5, head_rx + 1.5, head_ry + 1.5, 14), seed + "hoodin", 0.25), CREAM, relief=False)
    s.add(cut(oval(cx + 0.5, head_cy, head_rx, head_ry, 14), seed + "H", 0.3), skin)
    s.head = (hx, hy, head_rx, head_ry)
    if season == "summer":
        lobes = {
            "man": [(hx - 5, hy - head_ry + 3, 6.5, 4.5), (hx + 2.5, hy - head_ry + 1.5, 6.5, 4.5), (hx - head_rx + 1.5, hy - 4, 3.5, 6.5)],
            "woman": [(hx - 4, hy - head_ry + 2.5, 7.5, 5), (hx + 4, hy - head_ry + 2, 6, 4.5), (hx - head_rx - 1, hy + 1, 4.5, 11), (hx - head_rx + 3, hy + 7, 4, 6)],
            "boy": [(hx - 3, hy - head_ry + 3, 7, 4.5), (hx + 3.5, hy - head_ry + 2.5, 6, 4.5)],
            "girl": [(hx - 3, hy - head_ry + 2.5, 7.5, 5), (hx + 3.5, hy - head_ry + 2, 6, 4.5), (hx - head_rx - 2, hy + 3, 4, 6), (hx + head_rx + 2, hy + 3, 4, 6)],
        }[kind]
        for i, (lx, ly, rx, ry) in enumerate(lobes):
            s.add(cut(oval(lx, ly, rx, ry, 10), seed + f"lobe{i}", 0.3), hair if not (kind == "boy") else gar["cap"])
        if kind == "boy":
            s.add(cut([(hx + 2, hy - head_ry + 3), (hx + head_rx + 5.5, hy - head_ry + 3.5), (hx + head_rx + 5.5, hy - head_ry + 6.5), (hx + 2, hy - head_ry + 6.5)], seed + "brim"), gar["cap"])
        if kind == "woman":
            s.add(cut([(hx - head_rx + 1, hy - head_ry + 4), (hx + head_rx - 2, hy - head_ry + 3), (hx + head_rx - 1.5, hy - head_ry + 6), (hx - head_rx + 1.5, hy - head_ry + 7)], seed + "band"), gar["belt"])
        if kind == "girl":
            for i, bx in enumerate((hx - head_rx - 2, hx + head_rx + 2)):
                s.add(cut(oval(bx, hy - 2.5, 2.4, 2.2, 8), seed + f"bow{i}", 0.2), gar["bow"], relief=False)
    else:
        if kind != "boy":
            s.add(cut(oval(hx, hy - head_ry + 1.5, head_rx + 1.5, 5.5, 12), seed + "hat", 0.3), gar["hat"])
            s.add(cut([(hx - head_rx - 2, hy - head_ry + 1.5), (hx + head_rx + 2, hy - head_ry + 1.5), (hx + head_rx + 2, hy - head_ry + 5), (hx - head_rx - 2, hy - head_ry + 5)], seed + "hatband"), gar["belt"] if kind != "girl" else CREAM)
            if kind == "girl":
                s.add(cut(oval(hx, hy - head_ry - 4, 3.2, 3.0, 10), seed + "pom", 0.25), CREAM)
    for points, fill, kw in carry_parts:
        s.add(points, fill, **kw)
    return s, hands


def trimmed(s: Sprite) -> Sprite:
    """The shipped trim applied verbatim, so the frame stays co-registered with what ships."""
    dx, dy = TRIM
    s.width_units, s.height_units = CANVAS
    for part in s.parts:
        part.points = [(x - dx, y - dy) for x, y in part.points]
    if s.head is not None:
        hx, hy, rx, ry = s.head
        s.head = (hx - dx, hy - dy, rx, ry)
    return s


def render(s: Sprite) -> bytes:
    svg = bpc.emit_svg(s, STYLE)
    r = raster.render_svg(svg)
    expected = (s.width_units * UNIT, s.height_units * UNIT)
    if r.size != expected:
        raise SystemExit(f"{s.name}: rendered {r.size}, expected {expected}")
    return svg, r


def check_reproduces_shipped() -> None:
    """The proof that this path is the shipped one: the shipped man, summer, three frames."""
    res = REPO / "app" / "src" / "main" / "res" / "drawable-nodpi"
    for frame in range(3):
        s, _ = walker("man", "summer", frame, None)
        s = bpc.faced(trimmed(s), STYLE)
        _, r = render(s)
        shipped = (res / f"{s.name}.png").read_bytes()
        same = r.png_bytes == shipped
        print(f"  reproduces shipped {s.name}: {'byte-identical' if same else 'DIFFERS'}")
        if not same:
            raise SystemExit("the generator no longer reproduces the shipped frame; stop and look")


def build() -> None:
    out = HERE / "carry_concepts"
    out.mkdir(parents=True, exist_ok=True)
    check_reproduces_shipped()
    hands: dict = {}
    total_bytes = 0
    decoded = 0
    count = 0
    for pose in POSES:
        for kind in ("man", "woman"):
            for season in ("summer", "winter"):
                for frame in range(3):
                    s, h = walker(kind, season, frame, pose)
                    s = bpc.faced(trimmed(s), STYLE)
                    svg, r = render(s)
                    (out / f"{s.name}.svg").write_text(svg + "\n", encoding="utf-8")
                    (out / f"{s.name}.png").write_bytes(r.png_bytes)
                    m = measure_raster(s.name, r)
                    box = m.content_bbox
                    if box[2] > CANVAS[0] * UNIT - 1:
                        print(f"  WARNING {s.name}: content box {box} touches the canvas edge")
                    dx, dy = TRIM
                    hands[f"{pose}/{kind}/{frame}"] = {
                        "hand": [round(h["hand"][0] - dx, 2), round(h["hand"][1] - dy, 2)],
                        "handle_top": [round(h["handle_top"][0] - dx, 2), round(h["handle_top"][1] - dy, 2)],
                    }
                    # the three tones, by the shipped recolour
                    base_png = out / f"{s.name}.png"
                    for tone, target in enumerate(skin_tool.TONES):
                        _, variant = skin_tool.recolour(base_png, skin_tool.SKIN_BASE[kind], target)
                        p = out / f"{s.name}_skin{tone}.png"
                        variant.save(p, format="PNG", optimize=False, compress_level=9)
                        total_bytes += p.stat().st_size
                        decoded += r.size[0] * r.size[1] * 4
                        count += 1
                    print(f"  {s.name}: {r.size[0]}x{r.size[1]} content {list(box)} base {base_png.stat().st_size} B")
    (out / "hands.json").write_text(json.dumps(hands, indent=1) + "\n", encoding="utf-8")
    print(f"tone PNGs: {count}, file bytes {total_bytes} ({total_bytes / 1024:.0f} KB), decoded {decoded} B; "
          f"per pose: {count // 3} PNGs, {total_bytes // 3 / 1024:.0f} KB")


if __name__ == "__main__":
    build()
