package com.paperscrape.livewallpaper.engine

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The three placement changes v4.17 makes to the ground, each asserted on what it produces.
 *
 * None of these restates a constant back to itself. The parasol assertion generates the layout a
 * theme actually gets and measures it; the pile assertions are about how many objects a slider
 * position draws; the leaf assertion reads the call site out of the renderer.
 */
class GroundPilesAndParasolsTest {

    // ------------------------------------------------------------------ parasols

    /**
     * **The defect, as the number it was reported as an impression of.**
     *
     * Houses and parasols were generated by the same call with the same slot arithmetic and the
     * same two depth bands, so parasol `i` and house `i` came out at the *same* `depthFraction` --
     * it is derived from `i`, not from the seed -- and within `0.07` of a tile of each other on x,
     * which is 76 px of 1080. A house's door is at its own centre, so that is where the umbrella
     * stood. This measures the generated layout rather than trusting the reasoning.
     */
    @Test
    fun `a parasol no longer stands at the centre of a house`() {
        var worst = Float.MAX_VALUE
        var pairs = 0
        for (themeId in ThemeCatalog.ALL.map { it.id }) {
            val layout = SceneObjectCatalog.layoutFor(themeId, ThemeCatalog.byId(themeId).accentColor)
            val houses = layout.staticObjects.filter { it.type == SceneObjectType.HOUSE }
            val parasols = layout.staticObjects.filter { it.type == SceneObjectType.PARASOL }
            if (houses.isEmpty() || parasols.isEmpty()) continue
            for (p in parasols) {
                // Only houses at the same depth can be the one a parasol is standing in front of:
                // a house two bands back is behind it, not beside it.
                val sameDepth = houses.filter { kotlin.math.abs(it.depthFraction - p.depthFraction) < 1e-4f }
                for (h in sameDepth) {
                    pairs++
                    val dx = kotlin.math.abs(h.tileFractionX - p.tileFractionX)
                    if (dx < worst) worst = dx
                }
            }
        }
        assertTrue("no parasol shares a depth with any house in any theme", pairs > 0)
        assertTrue(
            "the nearest same-depth parasol is ${"%.4f".format(worst)} of a tile from a house " +
                "centre, which is back inside the doorway the phase exists to clear",
            worst >= 0.04f,
        )
    }

    /** Every house has exactly one, on alternating sides, so a street does not lean one way. */
    @Test
    fun `each house gets one parasol and the sides alternate`() {
        val layout = SceneObjectCatalog.layoutFor("sunset", ThemeCatalog.byId("sunset").accentColor)
        val houses = layout.staticObjects.filter { it.type == SceneObjectType.HOUSE }
        val parasols = layout.staticObjects.filter { it.type == SceneObjectType.PARASOL }
        assertEquals("one parasol per house", houses.size, parasols.size)
        val sides = houses.zip(parasols).map { (h, p) -> p.tileFractionX > h.tileFractionX }
        assertTrue("they must not all stand on the same side", sides.toSet().size == 2)
    }

    // ------------------------------------------------------------------ piles

    /**
     * 0% draws nothing, not one.
     *
     * The whole promise of the two sliders defaulting to zero is that a scene nobody has touched
     * costs what it cost before they existed, and that is only true if the loop does not run.
     */
    @Test
    fun `the slider is the number of piles, and zero means none`() {
        assertEquals(0, SceneObjectRenderer.pileCount(0f))
        assertEquals(0, SceneObjectRenderer.pileCount(0.04f))
        assertEquals(SceneObjectRenderer.PILE_MAX_COUNT / 2, SceneObjectRenderer.pileCount(0.5f))
        assertEquals(SceneObjectRenderer.PILE_MAX_COUNT, SceneObjectRenderer.pileCount(1f))
        assertEquals(SceneObjectRenderer.PILE_MAX_COUNT, SceneObjectRenderer.pileCount(4f))
        assertEquals(0, SceneObjectRenderer.pileCount(-1f))
    }

    /** Both default to nothing, so v4.16's scene is v4.17's scene until somebody moves a slider. */
    @Test
    fun `both piles default to off on every theme`() {
        for (themeId in ThemeCatalog.ALL.map { it.id }) {
            val c = defaultCustomizationFor(themeId)
            assertEquals("$themeId snow piles", 0f, c.snowPiles, 0f)
            assertEquals("$themeId leaf piles", 0f, c.leafPiles, 0f)
        }
    }

    /**
     * Each is gated on its own season, read from the renderer rather than from a list here.
     *
     * Snow drifts on a summer lawn and leaf heaps under a snow-capped tree are both wrong, and the
     * seasons already say which is which -- so the gate is `winterColorsEnabled` and
     * `fallColorsEnabled` and not a third switch. Asserted by reading `drawGroundPiles`, so moving
     * the gate fails here instead of shipping.
     */
    @Test
    fun `each pile kind is gated on its own season at the call site`() {
        val body = rendererSource().readText()
            .substringAfter("private fun drawGroundPiles(")
            .substringBefore("private fun scatterPiles(")
        assertTrue("snow piles must be inside a winterColorsEnabled branch", body.contains("customization.winterColorsEnabled"))
        assertTrue("leaf piles must be inside a fallColorsEnabled branch", body.contains("customization.fallColorsEnabled"))
        val snowAt = body.indexOf("snowPiles")
        val leafAt = body.indexOf("leafPiles")
        val winterAt = body.indexOf("winterColorsEnabled")
        val fallAt = body.indexOf("fallColorsEnabled")
        assertTrue("snowPiles must sit under the winter gate", winterAt in 0 until snowAt && snowAt < fallAt)
        assertTrue("leafPiles must sit under the autumn gate", fallAt in 0 until leafAt)
    }

    // ------------------------------------------------------------------ falling leaves

    /**
     * A leaf ends its fall at its own tree's foot, read from the call site.
     *
     * It used to end at one global `screenHeight * 0.88`, which is below both traffic lanes
     * (0.834 and 0.862), so leaves from every tree crossed the hillside and settled on the road
     * among the cars. Asserted against the source because the alternative -- rendering autumn and
     * looking for orange pixels -- cannot tell a leaf from the autumn canopy it fell off.
     */
    @Test
    fun `a falling leaf ends at its own tree's ground line`() {
        val body = File(rendererSource().parentFile, "PaperRenderer.kt").readText()
            .substringAfter("private fun drawFallingLeaves(")
            .substringBefore("\n    private fun ")
        assertTrue(
            "the fall must end at the source's own ground line",
            body.contains("val fallEndY = objectRenderer.leafSourceGroundY[source]"),
        )
        assertTrue(
            "no global fall floor may come back",
            !body.contains("screenHeight * 0.88f"),
        )
    }

    private companion object {
        fun rendererSource(): File {
            val suffix = "src/main/kotlin/com/paperscrape/livewallpaper/engine/SceneObjectRenderer.kt"
            var dir: File? = File(".").absoluteFile
            while (dir != null) {
                for (prefix in listOf("", "app/")) {
                    val candidate = File(dir, "$prefix$suffix")
                    if (candidate.isFile) return candidate
                }
                dir = dir.parentFile
            }
            error("could not locate $suffix")
        }
    }
}
