package com.paperscrape.livewallpaper.engine

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * [ShopPlanTable] is the shop plan, to the bit.
 *
 * The app stopped computing the plan when it starts (v5.10B): it cost ~566 ms of the main thread on
 * the BV6600 at every start of the wallpaper, for an answer that depends only on constants of the
 * code. [SceneObjectCatalog.planShopPositions] is still here and still the authority; this test runs
 * it and holds the table to its output. Anything that moves a shop's plan -- a street's generator, a
 * shop's width, an occluder -- fails here first, with the table it should now be written to
 * `app/build/shop-plan/ShopPlanTable.kt`, to be copied over the committed one.
 */
class ShopPlanTableTest {

    @Test
    fun `the committed table is the plan the planner computes, bit for bit`() {
        val planned = SceneObjectCatalog.planShopPositions()
        val folder = File("build/shop-plan").apply { mkdirs() }
        val written = File(folder, "ShopPlanTable.kt")
        written.writeText(ShopPlanTableSource.render(planned))
        val problems = ArrayList<String>()
        for ((id, x) in planned) {
            val table = ShopPlanTable.SHOP_X[id]
            when {
                x == null && table != null -> problems += "$id: the planner parks its shops by the fallback, the table places them"
                x != null && table == null -> problems += "$id: the planner places its shops, the table has no row for it"
                x != null && table != null && !x.map { it.toRawBits() }.equals(table.map { it.toRawBits() }) ->
                    problems += "$id: planned ${x.joinToString()} against the table's ${table.joinToString()}"
            }
        }
        for (id in ShopPlanTable.SHOP_X.keys - planned.keys) problems += "$id: in the table, not a built-in street"
        if (problems.isNotEmpty()) {
            fail(
                "ShopPlanTable is not the plan (${problems.size}):\n" + problems.joinToString("\n") +
                    "\nThe table it should be is in ${written.absolutePath}; copy it over " +
                    "app/src/main/kotlin/com/paperscrape/livewallpaper/engine/ShopPlanTable.kt.",
            )
        }
    }

    /**
     * The streets the app lays out from the table are the streets the planner would have laid out:
     * every static object of every built-in theme, every field, in order. The positions above could
     * agree while the table were applied to the wrong shop; this is what would catch it. A layout is
     * the street followed by the theme's decorations (`layoutFor` appends them), so the street is its
     * first part.
     */
    @Test
    fun `every built-in street laid out from the table is the street the planner lays out`() {
        val planned = SceneObjectCatalog.plannedStreets()
        assertEquals(12, planned.size)
        for ((id, objects) in planned) {
            val laidOut = SceneObjectCatalog.layoutFor(id, 0xFF8899AA.toInt()).staticObjects
            assertTrue("$id: a layout shorter than its street", laidOut.size >= objects.size)
            assertEquals("$id: the street laid out from ShopPlanTable", objects, laidOut.subList(0, objects.size))
        }
    }
}

/** The source of [ShopPlanTable] for a plan: what the first test writes out. */
internal object ShopPlanTableSource {
    fun render(planned: Map<String, FloatArray?>): String = buildString {
        appendLine("package com.paperscrape.livewallpaper.engine")
        appendLine()
        appendLine("/**")
        appendLine(" * Where the shops of each built-in street stand: [SceneObjectCatalog.planShopPositions]'s answer,")
        appendLine(" * computed when this table was generated instead of at every start of the app (v5.10B).")
        appendLine(" *")
        appendLine(" * **Generated by `ShopPlanTableTest`; do not edit by hand.** A theme's row is its shops'")
        appendLine(" * `tileFractionX`, deepest first -- restaurant, school, bar. A theme the plan could not place")
        appendLine(" * has no row, and its street parks its shops the way the planner does then. The test fails")
        appendLine(" * whenever this is not the planner's output to the bit, and writes the table it should be to")
        appendLine(" * `app/build/shop-plan/ShopPlanTable.kt`. Each value is the float's exact bits, with the")
        appendLine(" * decimal beside it for a reader.")
        appendLine(" */")
        appendLine("internal object ShopPlanTable {")
        appendLine("    val SHOP_X: Map<String, FloatArray> = mapOf(")
        for ((id, x) in planned) {
            if (x == null) continue
            val values = x.joinToString(", ") { "Float.fromBits(0x%08x) /* %s */".format(it.toRawBits(), it.toString()) }
            appendLine("        \"$id\" to floatArrayOf($values),")
        }
        appendLine("    )")
        appendLine("}")
    }
}
