"""Report output: machine-readable JSON, readable markdown, and one image.

All three are written for every run. The JSON is what a later phase reads, the
markdown is what a human reviews, and the sheet is the only one of the three that
can catch the failure the numbers cannot: a reconstruction that scores well and
still looks wrong. `AI_PROJECT_RULES.md` section 6.8 requires that an asset be
looked at, not read about, and a metric table is reading about it.

The sheet composites each sprite over a mid-tone background rather than over
white or over a checkerboard. These sprites are white silhouettes: on white they
are invisible, and a checkerboard hides exactly the soft edge the comparison is
about.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

from .fidelity import FidelityResult
from .inventory import SpriteMeasurement

#: Mid-tone slate. Chosen so a white silhouette and its antialiased edge are both
#: visible against it, and so the difference column's red reads clearly.
SHEET_BACKGROUND = (108, 132, 150, 255)
SHEET_CELL = 150
SHEET_LABEL_HEIGHT = 16


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def inventory_markdown(measurements: list[SpriteMeasurement], duplicates: dict[str, list[str]]) -> str:
    total_decoded = sum(m.decoded_bytes for m in measurements)
    total_padding = sum(m.transparent_padding_bytes for m in measurements)
    total_files = sum(m.file_bytes for m in measurements)
    unique = len({m.sha256 for m in measurements})
    off_grid = [m.name for m in measurements if not m.on_grid]

    lines = [
        "# Runtime sprite inventory",
        "",
        "Generated by `paperscrape-assets inventory`. Every figure here is measured",
        "from the shipped PNGs; nothing is copied from documentation.",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Files | {len(measurements)} |",
        f"| Unique contents | {unique} |",
        f"| Bytes on disk | {total_files / 1024:.1f} KB |",
        f"| Decoded `ARGB_8888` | {total_decoded / 1e6:.2f} MB |",
        f"| Of which transparent padding | {total_padding / 1e6:.2f} MB "
        f"({100 * total_padding / total_decoded:.0f} %) |",
        f"| Off the 3x authoring grid | {len(off_grid)} |",
        f"| Byte-identical duplicate groups | {len(duplicates)} |",
        "",
    ]

    if off_grid:
        lines += ["Off-grid: " + ", ".join(f"`{n}`" for n in sorted(off_grid)), ""]

    if duplicates:
        lines += ["## Byte-identical groups", "", "| Members |", "|---|"]
        for names in sorted(duplicates.values()):
            lines.append("| " + ", ".join(f"`{n}`" for n in names) + " |")
        lines.append("")

    lines += [
        "## Heaviest decoded sprites",
        "",
        "| Sprite | Size | Decoded | Padding |",
        "|---|---|---|---|",
    ]
    for m in sorted(measurements, key=lambda x: -x.decoded_bytes)[:10]:
        lines.append(
            f"| `{m.name}` | {m.width}x{m.height} | {m.decoded_bytes / 1e6:.2f} MB "
            f"| {100 * m.transparent_padding_fraction:.0f} % |"
        )
    lines.append("")

    lines += [
        "## Every sprite",
        "",
        "| Sprite | Size | Mode | Content bbox | Padding | Opaque RGB | Grid |",
        "|---|---|---|---|---|---|---|",
    ]
    for m in sorted(measurements, key=lambda x: x.name):
        box = "-" if m.content_bbox is None else ",".join(str(v) for v in m.content_bbox)
        lines.append(
            f"| `{m.name}` | {m.width}x{m.height} | {m.mode} | {box} "
            f"| {100 * m.transparent_padding_fraction:.0f} % | {m.opaque_rgb_count} "
            f"| {'yes' if m.on_grid else 'NO'} |"
        )
    return "\n".join(lines) + "\n"


def fidelity_markdown(results: list[FidelityResult], gaps: list[tuple[str, str]]) -> str:
    by_verdict: dict[str, int] = {}
    for r in results:
        by_verdict[r.verdict] = by_verdict.get(r.verdict, 0) + 1

    lines = [
        "# Staged reconstruction fidelity",
        "",
        "Generated by `paperscrape-assets compare`. Each row compares a sprite",
        "rendered from its committed SVG source against the PNG the app ships",
        "today. **No shipped PNG is modified by this pipeline.**",
        "",
        "Verdicts are defined in `paperscrape_assets/fidelity.py`. In short:",
        "`PIXEL_IDENTICAL` means all four channels match everywhere;",
        "`EDGE_EQUIVALENT` means no pixel where one image is solid and the other",
        "empty, an exact fill colour, and every differing pixel confined to the",
        "antialiased boundary; `DIVERGENT` means the geometry was not recovered.",
        "`IoU` is reported but does not gate: it is an area ratio, and an",
        "antialiased boundary is a fixed share of the perimeter, so a single",
        "absolute threshold asks small sprites for more precision than large ones.",
        "",
        "| Verdict | Sprites |",
        "|---|---|",
    ]
    for verdict in ("PIXEL_IDENTICAL", "EDGE_EQUIVALENT", "DIVERGENT"):
        lines.append(f"| `{verdict}` | {by_verdict.get(verdict, 0)} |")
    lines += ["", "## Per sprite", "",
              "| Sprite | Size | IoU | Mean alpha diff | Max alpha diff "
              "| Differing px | Solid/empty conflicts | Edge-confined | Max RGB diff "
              "| bbox delta | Verdict |",
              "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in sorted(results, key=lambda x: (x.verdict, x.name)):
        delta = "-" if r.bbox_delta is None else ",".join(str(v) for v in r.bbox_delta)
        lines.append(
            f"| `{r.name}` | {r.reference_size[0]}x{r.reference_size[1]} "
            f"| {r.alpha_iou:.6f} | {r.mean_alpha_diff:.4f} | {r.max_alpha_diff} "
            f"| {r.differing_pixels} / {r.total_pixels} | {r.interior_alpha_mismatch} "
            f"| {'yes' if r.boundary_confined else 'NO'} "
            f"| {r.max_rgb_diff_where_opaque} | {delta} | `{r.verdict}` |"
        )

    lines += [
        "",
        "## Sprites with no recoverable source",
        "",
        "These ship today and cannot be regenerated. Listed so the gap is a",
        "recorded state of the project rather than an omission from a report.",
        "",
        "| Sprite | Why |",
        "|---|---|",
    ]
    for name, reason in sorted(gaps):
        lines.append(f"| `{name}` | {reason} |")
    return "\n".join(lines) + "\n"


def _cell(image: Image.Image, size: int) -> Image.Image:
    canvas = Image.new("RGBA", (size, size), SHEET_BACKGROUND)
    fitted = image.copy()
    fitted.thumbnail((size - 8, size - 8), Image.LANCZOS)
    canvas.alpha_composite(fitted, ((size - fitted.width) // 2, (size - fitted.height) // 2))
    return canvas


def _difference_image(reference: np.ndarray, candidate: np.ndarray) -> Image.Image:
    """Alpha difference, amplified, in red. Black means the two agree exactly."""
    diff = np.abs(reference[..., 3].astype(np.int32) - candidate[..., 3].astype(np.int32))
    amplified = np.clip(diff * 4, 0, 255).astype(np.uint8)
    out = np.zeros((*diff.shape, 4), dtype=np.uint8)
    out[..., 0] = amplified
    out[..., 3] = 255
    return Image.fromarray(out, mode="RGBA")


def comparison_sheet(
    path: Path,
    rows: list[tuple[str, np.ndarray, np.ndarray]],
    cell: int = SHEET_CELL,
) -> None:
    """Three columns per sprite: shipped, staged, amplified difference."""
    if not rows:
        return
    width = cell * 3
    row_height = cell + SHEET_LABEL_HEIGHT
    sheet = Image.new("RGBA", (width, row_height * len(rows)), (28, 32, 38, 255))
    draw = ImageDraw.Draw(sheet)

    for index, (name, reference, candidate) in enumerate(rows):
        y = index * row_height
        ref_image = Image.fromarray(reference, mode="RGBA")
        cand_image = Image.fromarray(candidate, mode="RGBA")
        sheet.paste(_cell(ref_image, cell), (0, y))
        sheet.paste(_cell(cand_image, cell), (cell, y))
        sheet.paste(_cell(_difference_image(reference, candidate), cell), (cell * 2, y))
        draw.text((6, y + cell + 3), f"{name}   shipped | staged | alpha diff x4",
                  fill=(220, 226, 232, 255))

    path.parent.mkdir(parents=True, exist_ok=True)
    sheet.convert("RGB").save(path, format="PNG", optimize=False, compress_level=9)
