package com.paperscrape.livewallpaper.engine

import com.paperscrape.livewallpaper.R

/**
 * Which drawables make up each person, now that a person is **drawn rather than shipped in every
 * colour** (v4.30).
 *
 * A shape is `[fixed, skin, head, top, bottom]`: the fixed art, then one weight mask per
 * colourable region, `0` where the shape has no such region. The engine draws the fixed layer and
 * then adds each mask multiplied by the colour that region is wearing this crossing --
 * `SceneObjectRenderer.drawPersonLayers`.
 *
 * **Generated by `tools/generate_people_layers.py`, which is also what writes the artwork.** Not
 * committed by hand: a shape that gains or loses a region -- a summer dress has no trousers, a
 * hood is part of a coat and not a hat -- would otherwise have to be remembered in two places, and
 * the second one is the one that goes stale. Regenerate both together or neither.
 */
internal object PeopleLayerTable {


    /** Slot of the fixed art in a shape's array. */
    const val FIXED = 0

    /** Slots of the four masks, in the order `PeopleColours` resolves their colours. */
    const val SKIN = 1
    const val HEAD = 2
    const val TOP = 3
    const val BOTTOM = 4

    /** How many drawables a shape carries: the fixed layer plus one slot per region. */
    const val SLOTS = 5

    /** The walkers: `[kind][season][frame]`. */
    val WALK = arrayOf(
        arrayOf(
            arrayOf(
                intArrayOf(R.drawable.person_man_summer_walk0_fx, R.drawable.person_man_summer_walk0_ms, R.drawable.person_man_summer_walk0_mh, R.drawable.person_man_summer_walk0_mt, R.drawable.person_man_summer_walk0_mb),
                intArrayOf(R.drawable.person_man_summer_walk1_fx, R.drawable.person_man_summer_walk1_ms, R.drawable.person_man_summer_walk1_mh, R.drawable.person_man_summer_walk1_mt, R.drawable.person_man_summer_walk1_mb),
                intArrayOf(R.drawable.person_man_summer_walk2_fx, R.drawable.person_man_summer_walk2_ms, R.drawable.person_man_summer_walk2_mh, R.drawable.person_man_summer_walk2_mt, R.drawable.person_man_summer_walk2_mb),
                intArrayOf(R.drawable.person_man_summer_walk1_fx, R.drawable.person_man_summer_walk1_ms, R.drawable.person_man_summer_walk1_mh, R.drawable.person_man_summer_walk1_mt, R.drawable.person_man_summer_walk1_mb),
            ),
            arrayOf(
                intArrayOf(R.drawable.person_man_winter_walk0_fx, R.drawable.person_man_winter_walk0_ms, R.drawable.person_man_winter_walk0_mh, R.drawable.person_man_winter_walk0_mt, R.drawable.person_man_winter_walk0_mb),
                intArrayOf(R.drawable.person_man_winter_walk1_fx, R.drawable.person_man_winter_walk1_ms, R.drawable.person_man_winter_walk1_mh, R.drawable.person_man_winter_walk1_mt, R.drawable.person_man_winter_walk1_mb),
                intArrayOf(R.drawable.person_man_winter_walk2_fx, R.drawable.person_man_winter_walk2_ms, R.drawable.person_man_winter_walk2_mh, R.drawable.person_man_winter_walk2_mt, R.drawable.person_man_winter_walk2_mb),
                intArrayOf(R.drawable.person_man_winter_walk1_fx, R.drawable.person_man_winter_walk1_ms, R.drawable.person_man_winter_walk1_mh, R.drawable.person_man_winter_walk1_mt, R.drawable.person_man_winter_walk1_mb),
            ),
        ),
        arrayOf(
            arrayOf(
                intArrayOf(R.drawable.person_woman_summer_walk0_fx, R.drawable.person_woman_summer_walk0_ms, R.drawable.person_woman_summer_walk0_mh, R.drawable.person_woman_summer_walk0_mt, 0),
                intArrayOf(R.drawable.person_woman_summer_walk1_fx, R.drawable.person_woman_summer_walk1_ms, R.drawable.person_woman_summer_walk1_mh, R.drawable.person_woman_summer_walk1_mt, 0),
                intArrayOf(R.drawable.person_woman_summer_walk2_fx, R.drawable.person_woman_summer_walk2_ms, R.drawable.person_woman_summer_walk2_mh, R.drawable.person_woman_summer_walk2_mt, 0),
                intArrayOf(R.drawable.person_woman_summer_walk1_fx, R.drawable.person_woman_summer_walk1_ms, R.drawable.person_woman_summer_walk1_mh, R.drawable.person_woman_summer_walk1_mt, 0),
            ),
            arrayOf(
                intArrayOf(R.drawable.person_woman_winter_walk0_fx, R.drawable.person_woman_winter_walk0_ms, R.drawable.person_woman_winter_walk0_mh, R.drawable.person_woman_winter_walk0_mt, R.drawable.person_woman_winter_walk0_mb),
                intArrayOf(R.drawable.person_woman_winter_walk1_fx, R.drawable.person_woman_winter_walk1_ms, R.drawable.person_woman_winter_walk1_mh, R.drawable.person_woman_winter_walk1_mt, R.drawable.person_woman_winter_walk1_mb),
                intArrayOf(R.drawable.person_woman_winter_walk2_fx, R.drawable.person_woman_winter_walk2_ms, R.drawable.person_woman_winter_walk2_mh, R.drawable.person_woman_winter_walk2_mt, R.drawable.person_woman_winter_walk2_mb),
                intArrayOf(R.drawable.person_woman_winter_walk1_fx, R.drawable.person_woman_winter_walk1_ms, R.drawable.person_woman_winter_walk1_mh, R.drawable.person_woman_winter_walk1_mt, R.drawable.person_woman_winter_walk1_mb),
            ),
        ),
        arrayOf(
            arrayOf(
                intArrayOf(R.drawable.person_boy_summer_walk0_fx, R.drawable.person_boy_summer_walk0_ms, R.drawable.person_boy_summer_walk0_mh, R.drawable.person_boy_summer_walk0_mt, R.drawable.person_boy_summer_walk0_mb),
                intArrayOf(R.drawable.person_boy_summer_walk1_fx, R.drawable.person_boy_summer_walk1_ms, R.drawable.person_boy_summer_walk1_mh, R.drawable.person_boy_summer_walk1_mt, R.drawable.person_boy_summer_walk1_mb),
                intArrayOf(R.drawable.person_boy_summer_walk2_fx, R.drawable.person_boy_summer_walk2_ms, R.drawable.person_boy_summer_walk2_mh, R.drawable.person_boy_summer_walk2_mt, R.drawable.person_boy_summer_walk2_mb),
                intArrayOf(R.drawable.person_boy_summer_walk1_fx, R.drawable.person_boy_summer_walk1_ms, R.drawable.person_boy_summer_walk1_mh, R.drawable.person_boy_summer_walk1_mt, R.drawable.person_boy_summer_walk1_mb),
            ),
            arrayOf(
                intArrayOf(R.drawable.person_boy_winter_walk0_fx, R.drawable.person_boy_winter_walk0_ms, 0, R.drawable.person_boy_winter_walk0_mt, R.drawable.person_boy_winter_walk0_mb),
                intArrayOf(R.drawable.person_boy_winter_walk1_fx, R.drawable.person_boy_winter_walk1_ms, 0, R.drawable.person_boy_winter_walk1_mt, R.drawable.person_boy_winter_walk1_mb),
                intArrayOf(R.drawable.person_boy_winter_walk2_fx, R.drawable.person_boy_winter_walk2_ms, 0, R.drawable.person_boy_winter_walk2_mt, R.drawable.person_boy_winter_walk2_mb),
                intArrayOf(R.drawable.person_boy_winter_walk1_fx, R.drawable.person_boy_winter_walk1_ms, 0, R.drawable.person_boy_winter_walk1_mt, R.drawable.person_boy_winter_walk1_mb),
            ),
        ),
        arrayOf(
            arrayOf(
                intArrayOf(R.drawable.person_girl_summer_walk0_fx, R.drawable.person_girl_summer_walk0_ms, R.drawable.person_girl_summer_walk0_mh, R.drawable.person_girl_summer_walk0_mt, 0),
                intArrayOf(R.drawable.person_girl_summer_walk1_fx, R.drawable.person_girl_summer_walk1_ms, R.drawable.person_girl_summer_walk1_mh, R.drawable.person_girl_summer_walk1_mt, 0),
                intArrayOf(R.drawable.person_girl_summer_walk2_fx, R.drawable.person_girl_summer_walk2_ms, R.drawable.person_girl_summer_walk2_mh, R.drawable.person_girl_summer_walk2_mt, 0),
                intArrayOf(R.drawable.person_girl_summer_walk1_fx, R.drawable.person_girl_summer_walk1_ms, R.drawable.person_girl_summer_walk1_mh, R.drawable.person_girl_summer_walk1_mt, 0),
            ),
            arrayOf(
                intArrayOf(R.drawable.person_girl_winter_walk0_fx, R.drawable.person_girl_winter_walk0_ms, R.drawable.person_girl_winter_walk0_mh, R.drawable.person_girl_winter_walk0_mt, R.drawable.person_girl_winter_walk0_mb),
                intArrayOf(R.drawable.person_girl_winter_walk1_fx, R.drawable.person_girl_winter_walk1_ms, R.drawable.person_girl_winter_walk1_mh, R.drawable.person_girl_winter_walk1_mt, R.drawable.person_girl_winter_walk1_mb),
                intArrayOf(R.drawable.person_girl_winter_walk2_fx, R.drawable.person_girl_winter_walk2_ms, R.drawable.person_girl_winter_walk2_mh, R.drawable.person_girl_winter_walk2_mt, R.drawable.person_girl_winter_walk2_mb),
                intArrayOf(R.drawable.person_girl_winter_walk1_fx, R.drawable.person_girl_winter_walk1_ms, R.drawable.person_girl_winter_walk1_mh, R.drawable.person_girl_winter_walk1_mt, R.drawable.person_girl_winter_walk1_mb),
            ),
        ),
    )

    /** The carrying pose, adults only: `[kind][season][frame]`. */
    val CARRY = arrayOf(
        arrayOf(
            arrayOf(
                intArrayOf(R.drawable.person_man_summer_carry0_fx, R.drawable.person_man_summer_carry0_ms, R.drawable.person_man_summer_walk0_mh, R.drawable.person_man_summer_carry0_mt, R.drawable.person_man_summer_carry0_mb),
                intArrayOf(R.drawable.person_man_summer_carry1_fx, R.drawable.person_man_summer_carry1_ms, R.drawable.person_man_summer_walk1_mh, R.drawable.person_man_summer_carry1_mt, R.drawable.person_man_summer_walk1_mb),
                intArrayOf(R.drawable.person_man_summer_carry2_fx, R.drawable.person_man_summer_carry2_ms, R.drawable.person_man_summer_walk2_mh, R.drawable.person_man_summer_carry2_mt, R.drawable.person_man_summer_walk2_mb),
                intArrayOf(R.drawable.person_man_summer_carry1_fx, R.drawable.person_man_summer_carry1_ms, R.drawable.person_man_summer_walk1_mh, R.drawable.person_man_summer_carry1_mt, R.drawable.person_man_summer_walk1_mb),
            ),
            arrayOf(
                intArrayOf(R.drawable.person_man_winter_carry0_fx, R.drawable.person_man_winter_carry0_ms, R.drawable.person_man_winter_walk0_mh, R.drawable.person_man_winter_carry0_mt, R.drawable.person_man_winter_walk0_mb),
                intArrayOf(R.drawable.person_man_winter_carry1_fx, R.drawable.person_man_winter_carry1_ms, R.drawable.person_man_winter_walk1_mh, R.drawable.person_man_winter_carry1_mt, R.drawable.person_man_winter_walk1_mb),
                intArrayOf(R.drawable.person_man_winter_carry2_fx, R.drawable.person_man_winter_carry2_ms, R.drawable.person_man_winter_walk2_mh, R.drawable.person_man_winter_carry2_mt, R.drawable.person_man_winter_walk2_mb),
                intArrayOf(R.drawable.person_man_winter_carry1_fx, R.drawable.person_man_winter_carry1_ms, R.drawable.person_man_winter_walk1_mh, R.drawable.person_man_winter_carry1_mt, R.drawable.person_man_winter_walk1_mb),
            ),
        ),
        arrayOf(
            arrayOf(
                intArrayOf(R.drawable.person_woman_summer_carry0_fx, R.drawable.person_woman_summer_carry0_ms, R.drawable.person_woman_summer_walk0_mh, R.drawable.person_woman_summer_carry0_mt, 0),
                intArrayOf(R.drawable.person_woman_summer_carry1_fx, R.drawable.person_woman_summer_carry1_ms, R.drawable.person_woman_summer_walk1_mh, R.drawable.person_woman_summer_carry1_mt, 0),
                intArrayOf(R.drawable.person_woman_summer_carry2_fx, R.drawable.person_woman_summer_carry2_ms, R.drawable.person_woman_summer_walk2_mh, R.drawable.person_woman_summer_carry2_mt, 0),
                intArrayOf(R.drawable.person_woman_summer_carry1_fx, R.drawable.person_woman_summer_carry1_ms, R.drawable.person_woman_summer_walk1_mh, R.drawable.person_woman_summer_carry1_mt, 0),
            ),
            arrayOf(
                intArrayOf(R.drawable.person_woman_winter_carry0_fx, R.drawable.person_woman_winter_carry0_ms, R.drawable.person_woman_winter_walk0_mh, R.drawable.person_woman_winter_carry0_mt, R.drawable.person_woman_winter_walk0_mb),
                intArrayOf(R.drawable.person_woman_winter_carry1_fx, R.drawable.person_woman_winter_carry1_ms, R.drawable.person_woman_winter_walk1_mh, R.drawable.person_woman_winter_carry1_mt, R.drawable.person_woman_winter_walk1_mb),
                intArrayOf(R.drawable.person_woman_winter_carry2_fx, R.drawable.person_woman_winter_carry2_ms, R.drawable.person_woman_winter_walk2_mh, R.drawable.person_woman_winter_carry2_mt, R.drawable.person_woman_winter_walk2_mb),
                intArrayOf(R.drawable.person_woman_winter_carry1_fx, R.drawable.person_woman_winter_carry1_ms, R.drawable.person_woman_winter_walk1_mh, R.drawable.person_woman_winter_carry1_mt, R.drawable.person_woman_winter_walk1_mb),
            ),
        ),
    )

    /**
     * The window busts: `[kind]`, **summer only**.
     *
     * There is no season axis any more, and its absence is the closure of `BACKLOG_v4_25.md` item
     * 57. Indoors the season index was always 0 -- *the hat belongs to the street, not to the room
     * behind the pane* -- so the winter column named twelve recolours no draw path could reach.
     * They are retired, and so is the column that pretended otherwise.
     */
    val WINDOW = arrayOf(
        intArrayOf(R.drawable.person_man_summer_head_window_fx, R.drawable.person_man_summer_head_window_ms, R.drawable.person_man_summer_head_window_mh, R.drawable.person_man_summer_head_window_mt, 0),
        intArrayOf(R.drawable.person_woman_summer_head_window_fx, R.drawable.person_woman_summer_head_window_ms, R.drawable.person_woman_summer_head_window_mh, R.drawable.person_woman_summer_head_window_mt, 0),
        intArrayOf(R.drawable.person_boy_summer_head_window_fx, R.drawable.person_boy_summer_head_window_ms, R.drawable.person_boy_summer_head_window_mh, R.drawable.person_boy_summer_head_window_mt, 0),
        intArrayOf(R.drawable.person_girl_summer_head_window_fx, R.drawable.person_girl_summer_head_window_ms, R.drawable.person_girl_summer_head_window_mh, R.drawable.person_girl_summer_head_window_mt, 0),
    )

    /** The seated busts: `[kind][season]`. */
    val CAR = arrayOf(
        arrayOf(
            intArrayOf(R.drawable.person_man_summer_head_car_fx, R.drawable.person_man_summer_head_car_ms, R.drawable.person_man_summer_head_car_mh, R.drawable.person_man_summer_head_car_mt, 0),
            intArrayOf(R.drawable.person_man_winter_head_car_fx, R.drawable.person_man_winter_head_car_ms, R.drawable.person_man_winter_head_car_mh, R.drawable.person_man_winter_head_car_mt, 0),
        ),
        arrayOf(
            intArrayOf(R.drawable.person_woman_summer_head_car_fx, R.drawable.person_woman_summer_head_car_ms, R.drawable.person_woman_summer_head_car_mh, R.drawable.person_woman_summer_head_car_mt, 0),
            intArrayOf(R.drawable.person_woman_winter_head_car_fx, R.drawable.person_woman_winter_head_car_ms, R.drawable.person_woman_winter_head_car_mh, R.drawable.person_woman_winter_head_car_mt, 0),
        ),
        arrayOf(
            intArrayOf(R.drawable.person_boy_summer_head_car_fx, R.drawable.person_boy_summer_head_car_ms, R.drawable.person_boy_summer_head_car_mh, R.drawable.person_boy_summer_head_car_mt, 0),
            intArrayOf(R.drawable.person_boy_winter_head_car_fx, R.drawable.person_boy_winter_head_car_ms, 0, R.drawable.person_boy_winter_head_car_mt, 0),
        ),
        arrayOf(
            intArrayOf(R.drawable.person_girl_summer_head_car_fx, R.drawable.person_girl_summer_head_car_ms, R.drawable.person_girl_summer_head_car_mh, R.drawable.person_girl_summer_head_car_mt, 0),
            intArrayOf(R.drawable.person_girl_winter_head_car_fx, R.drawable.person_girl_winter_head_car_ms, R.drawable.person_girl_winter_head_car_mh, R.drawable.person_girl_winter_head_car_mt, 0),
        ),
    )

    /**
     * Whether this family wears something on its head in this season instead of showing hair:
     * `[kind][season]`.
     *
     * It decides which palette the head region draws from -- hair colours for a bare head, cap
     * colours for a covered one -- and it is a fact about the drawing, so it is written here by
     * the generator that drew it rather than restated in the engine.
     *
     * The winter boy reads `true` and has no head mask at all: what he wears is his own coat's
     * hood, which is drawn in the coat's paint and belongs to the top region. His head changes
     * colour with his coat, which is what a hood does.
     */
    val HEAD_WORN = arrayOf(
        booleanArrayOf(false, true),   // man
        booleanArrayOf(false, true),   // woman
        booleanArrayOf(true, true),   // boy
        booleanArrayOf(false, true),   // girl
    )
}
