package com.paperscrape.livewallpaper.engine

/**
 * Where the shops of each built-in street stand: [SceneObjectCatalog.planShopPositions]'s answer,
 * computed when this table was generated instead of at every start of the app (v5.10B).
 *
 * **Generated by `ShopPlanTableTest`; do not edit by hand.** A theme's row is its shops'
 * `tileFractionX`, deepest first -- restaurant, school, bar. A theme the plan could not place
 * has no row, and its street parks its shops the way the planner does then. The test fails
 * whenever this is not the planner's output to the bit, and writes the table it should be to
 * `app/build/shop-plan/ShopPlanTable.kt`. Each value is the float's exact bits, with the
 * decimal beside it for a reader.
 */
internal object ShopPlanTable {
    val SHOP_X: Map<String, FloatArray> = mapOf(
        "sunset" to floatArrayOf(Float.fromBits(0x3f2e147b) /* 0.68 */, Float.fromBits(0x3ee66666) /* 0.45 */, Float.fromBits(0x3de147ae) /* 0.11 */),
        "autumn" to floatArrayOf(Float.fromBits(0x3e4ccccc) /* 0.19999999 */, Float.fromBits(0x3ed1eb85) /* 0.41 */, Float.fromBits(0x3cf5c28f) /* 0.03 */),
        "winter" to floatArrayOf(Float.fromBits(0x3efae147) /* 0.48999998 */, Float.fromBits(0x3e8a3d70) /* 0.26999998 */, Float.fromBits(0x3eb851eb) /* 0.35999998 */),
        "desert" to floatArrayOf(Float.fromBits(0x3ecccccc) /* 0.39999998 */, Float.fromBits(0x3ca3d70a) /* 0.02 */, Float.fromBits(0x3e4ccccc) /* 0.19999999 */),
        "christmas" to floatArrayOf(Float.fromBits(0x3e999999) /* 0.29999998 */, Float.fromBits(0x3e051eb8) /* 0.13 */, Float.fromBits(0x3f2b851e) /* 0.66999996 */),
        "new_year" to floatArrayOf(Float.fromBits(0x3f000000) /* 0.5 */, Float.fromBits(0x3c23d70a) /* 0.01 */, Float.fromBits(0x3f2b851e) /* 0.66999996 */),
        "beach" to floatArrayOf(Float.fromBits(0x3cf5c28f) /* 0.03 */, Float.fromBits(0x3e0f5c29) /* 0.14 */, Float.fromBits(0x3e8f5c29) /* 0.28 */),
        "city" to floatArrayOf(Float.fromBits(0x3e8a3d70) /* 0.26999998 */, Float.fromBits(0x3c23d70a) /* 0.01 */, Float.fromBits(0x3f000000) /* 0.5 */),
        "tundra" to floatArrayOf(Float.fromBits(0x3efae147) /* 0.48999998 */, Float.fromBits(0x3e8a3d70) /* 0.26999998 */, Float.fromBits(0x3cf5c28f) /* 0.03 */),
        "easter" to floatArrayOf(Float.fromBits(0x3d8f5c29) /* 0.07 */, Float.fromBits(0x3ee147ae) /* 0.44 */, Float.fromBits(0x3e4ccccc) /* 0.19999999 */),
        "halloween" to floatArrayOf(Float.fromBits(0x3ca3d70a) /* 0.02 */, Float.fromBits(0x3e8a3d70) /* 0.26999998 */, Float.fromBits(0x3de147ae) /* 0.11 */),
        "spring" to floatArrayOf(Float.fromBits(0x3e947ae1) /* 0.29 */, Float.fromBits(0x3e051eb8) /* 0.13 */, Float.fromBits(0x3f147ae1) /* 0.58 */),
    )
}
