#!/usr/bin/env python3
"""v4.28 phase-1 concepts: a bird that reads its own direction, an umbrella for the walkers, and
whitecaps that pass over the water in bad weather. Proposals only -- nothing here is shipped.

Run from ``tools/assets`` with the pinned venv:

    /home/bober/.venvs/paperscrape-assets/bin/python concepts/rainbird/build_rainbird_concepts.py

Writes ``concepts/rainbird/<family>/<name>.svg`` and ``.png`` and a ``sprites.concept.json`` per
family, rendered through the project's own rasteriser (``paperscrape_assets.raster``). The cut
edges reuse the wobble helpers of the v4.26 sky-and-water generator
(``concepts/skywater/build_skywater_concepts.py``); nothing is traced or sampled from anywhere.

Three families, three proposals each:

**Birds** -- 51x21 canvas pixels, ``CANVAS_PIXELS``, flap axis at row 15, tintable mask: the
shipped canvas, origin and call site. The shipped "Colomba" raises both wings *forward*, and at
48 px the two humps are the largest shape in the outline and read as a fanned tail, so the eye
turns the animal round. All three proposals move the largest shape behind the head:

    B1 "Rondine"           deep forked tail, sickle wings swept back, small head, short beak
    B2 "Gabbiano lungo"    long shallow-V wings tilted back, a longer neck and beak, wedge tail
    B3 "Colomba corretta"  the shipped body, wings rotated back, a longer beak, a notched fan

**Umbrellas** -- ``SCENE_UNITS`` (3 px per unit), tintable mask, one sprite for every walker: it
is a separate blit drawn in the figure's own transform, so season, tone, family and direction
cost nothing. The handle is a rectangle drawn in code (the parasol pole's recipe). Panels
alternate white and a light grey, which is the parasol's stripe fan said as a mask.

    U1 "Alta"        a round dome, 48x24 units      (O1 upright, O2 = O1 rotated 12 deg)
    U3 "Piatta"      a shallow wide canopy, 54x18   (O3)

**Waves** -- ``SCENE_UNITS``, tintable mask, **foam only**: the body of the wave is transparent,
so the mirror shows through and what is drawn is the whitecap and a band of shade under it. One
blit per wave, tinted with a colour derived per frame from the water's own surface.

    W1 "Cavallone"      one curling crest with a frothy lip, two frames, 84x24 units
    W2 "Cresta doppia"  two low foam patches on one swell, 96x18
    W3 "Increspature"   a small foam tick, 36x12
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TOOL_ROOT = HERE.parent.parent
sys.path.insert(0, str(TOOL_ROOT))
sys.path.insert(0, str(TOOL_ROOT / "concepts" / "skywater"))

from build_skywater_concepts import UNIT, cut, circle_pts  # noqa: E402
from paperscrape_assets import raster  # noqa: E402
from paperscrape_assets.inventory import measure_raster  # noqa: E402

WHITE = "#FFFFFF"
PAPER_1 = "#F4F4F4"
PAPER_2 = "#EAEAEA"
PAPER_3 = "#E0E0E0"   # 12.5 % below white: the darkest a tintable mask may carry (14 %)


# ------------------------------------------------------------------------------ svg plumbing
def poly(points, fill: str) -> str:
    return '<polygon points="' + " ".join(f"{x:.2f},{y:.2f}" for x, y in points) + f'" fill="{fill}"/>'


def svg_doc(width_px: int, height_px: int, view_w: float, view_h: float, comment: str, body: list[str]) -> str:
    return "\n".join(
        [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width_px}" height="{height_px}" viewBox="0 0 {view_w:g} {view_h:g}">',
         f"<!-- {comment} Generated by tools/assets/concepts/rainbird/build_rainbird_concepts.py; "
         "the wobble is written into the coordinates, nothing is computed at runtime. -->"]
        + body + ["</svg>"]
    )


def ellipse_arc(cx, cy, rx, ry, t0, t1, n):
    """Points on an ellipse from angle t0 to t1 (radians), n+1 points."""
    return [(cx + rx * math.cos(t0 + (t1 - t0) * i / n), cy + ry * math.sin(t0 + (t1 - t0) * i / n))
            for i in range(n + 1)]


# ------------------------------------------------------------------------------ the birds
BIRD_W, BIRD_H, AXIS = 51, 21, 15.0
BIRD_WOBBLE = 0.4   # the sprite is drawn 1:1, so a cut wider than half a pixel is a cut


def bird_rondine() -> list[str]:
    a = AXIS
    far_wing = [(35, a - 3.2), (31, a - 5.6), (25, a - 8.6), (19, a - 11.0), (15, a - 12.0),
                (18, a - 9.8), (22.5, a - 7.2), (26, a - 4.4), (27.5, a - 2.6)]
    body = [(12, a - 1.6), (18, a - 2.8), (27, a - 3.4), (35, a - 3.2), (40, a - 2.4), (43.5, a - 2.4),
            (46.5, a - 1.0), (49.5, a - 0.2), (46, a + 1.2), (43, a + 2.4), (38, a + 3.0), (30, a + 3.4),
            (20, a + 3.2), (13, a + 2.2)]
    tail = [(14, a - 1.6), (2.5, a - 4.6), (4.5, a - 2.4), (11.5, a), (4.5, a + 2.6), (2.5, a + 4.6), (14, a + 2.0)]
    near_wing = [(33, a - 3.0), (29, a - 6.0), (23, a - 9.6), (16, a - 12.6), (10.5, a - 13.8),
                 (13.5, a - 11.4), (18.5, a - 8.4), (22.5, a - 4.8), (24.5, a - 2.4)]
    return [poly(cut(far_wing, "b1-far", BIRD_WOBBLE), PAPER_2),
            poly(cut(tail, "b1-tail", BIRD_WOBBLE), WHITE),
            poly(cut(body, "b1-body", BIRD_WOBBLE), WHITE),
            poly(cut(near_wing, "b1-near", BIRD_WOBBLE), WHITE)]


def bird_gabbiano_lungo() -> list[str]:
    a = AXIS
    far_wing = [(36, a - 3.0), (32, a - 5.0), (26, a - 7.6), (19, a - 10.4), (12.5, a - 12.4),
                (15, a - 10.0), (20, a - 7.4), (25.5, a - 4.6), (29, a - 2.8)]
    body = [(11, a - 1.4), (18, a - 2.6), (27, a - 3.2), (35, a - 3.0), (39.5, a - 2.6), (42.5, a - 3.2),
            (45.5, a - 3.0), (47.8, a - 1.6), (50.6, a - 0.4), (47.2, a + 0.6), (44.5, a + 1.6), (41, a + 2.6),
            (35, a + 3.4), (26, a + 3.6), (18, a + 3.2), (12, a + 2.0)]
    tail = [(12, a - 1.4), (4.5, a - 1.0), (3, a + 0.2), (4.5, a + 1.6), (12, a + 2.0)]
    near_wing = [(34, a - 3.0), (28, a - 6.4), (20, a - 10.2), (12, a - 13.0), (6, a - 13.6),
                 (9, a - 11.2), (14, a - 8.2), (19, a - 5.0), (22, a - 2.6)]
    return [poly(cut(far_wing, "b2-far", BIRD_WOBBLE), PAPER_2),
            poly(cut(tail, "b2-tail", BIRD_WOBBLE), WHITE),
            poly(cut(body, "b2-body", BIRD_WOBBLE), WHITE),
            poly(cut(near_wing, "b2-near", BIRD_WOBBLE), WHITE)]


def bird_colomba_corretta() -> list[str]:
    """The shipped Colomba's body, head and beak, with the wings rotated to point back."""
    a = AXIS
    far_wing = [(27, a - 2.8), (24, a - 6.8), (19, a - 10.6), (13.5, a - 12.6), (13, a - 10.6),
                (17, a - 7.6), (21.5, a - 4.4), (23, a - 2.4)]
    body = [(12, a + 1), (10.5, a - 2), (14, a - 4.6), (22, a - 5), (36, a - 4), (40.5, a - 3.4), (42, a - 1),
            (42, a + 1), (41, a + 3.6), (38, a + 5), (30, a + 5), (16, a + 5), (11.5, a + 3.8)]
    tail = [(13.5, a - 2.8), (4, a - 2.6), (7, a + 0.3), (4, a + 3.3), (13.5, a + 3.6)]
    near_wing = [(31.5, a - 3.2), (28, a - 7.4), (23.5, a - 11.6), (18, a - 13.6), (16.5, a - 11.8),
                 (20, a - 8.2), (23.5, a - 4.6), (25, a - 2.2)]
    beak = [(45.5, a - 1.8), (50.5, a - 0.6), (45.5, a + 0.6)]
    return [poly(cut(far_wing, "b3-far", BIRD_WOBBLE), PAPER_2),
            poly(cut(tail, "b3-tail", BIRD_WOBBLE), WHITE),
            poly(cut(body, "b3-body", BIRD_WOBBLE), WHITE),
            poly(cut(near_wing, "b3-near", BIRD_WOBBLE), WHITE),
            poly(cut(circle_pts(43.0, a - 1.0, 3.6, 14), "b3-head", 0.25), WHITE),
            poly(beak, WHITE)]


BIRDS = {
    "bird_concept1": ("B1 Rondine: forked tail, sickle wings swept back.", bird_rondine),
    "bird_concept2": ("B2 Gabbiano lungo: long shallow-V wings tilted back, longer neck and beak.", bird_gabbiano_lungo),
    "bird_concept3": ("B3 Colomba corretta: the shipped body with the wings rotated back and a longer beak.", bird_colomba_corretta),
}


# ------------------------------------------------------------------------------ the umbrellas
def canopy(width: float, height: float, panels: int, scallop: float, seed: str) -> list[str]:
    """A side view of an open canopy: one half-ellipse of paper whose rim sags into a scallop
    between the ribs, with every other panel laid over it in a lighter grey, and a ferrule nub at
    the crown. The ribs run from the crown down the visible face to the rim, so a panel is a
    wedge from the crown to one scallop of the bottom edge; their feet are spaced as a dome's ribs
    project from the side, denser toward the ends."""
    cx, rim_y = width / 2, height - scallop - 0.5
    rx, ry = width / 2 - 1.0, rim_y - 3.0
    crown = (cx, 3.0)
    feet = [(cx - rx * math.cos(math.pi * k / panels), rim_y) for k in range(panels + 1)]

    def sag(a, b):
        (x0, y0), (x1, y1) = a, b
        return [(x0, y0), ((x0 * 2 + x1) / 3, y0 + scallop * 0.8), ((x0 + x1) / 2, y0 + scallop),
                ((x0 + x1 * 2) / 3, y0 + scallop * 0.8), (x1, y1)]

    top = ellipse_arc(cx, rim_y, rx, ry, math.pi, 2 * math.pi, 28)
    bottom = []
    for k in range(panels - 1, -1, -1):
        bottom += sag(feet[k], feet[k + 1])[::-1][:-1]
    out = [poly([(cx - 1.5, 0.0), (cx + 1.5, 0.0), (cx + 1.5, 3.5), (cx - 1.5, 3.5)], PAPER_3),
           poly(cut(top + bottom, f"{seed}-dome", 0.35), WHITE)]
    for k in range(1, panels, 2):
        pts = [crown] + sag(feet[k], feet[k + 1])
        out.append(poly(cut(pts, f"{seed}-{k}", 0.3), PAPER_2))
    return out


UMBRELLAS = {
    "umbrella_concept1": (48, 24, "U1 Alta: a round dome of six panels.", lambda: canopy(48, 24, 6, 2.2, "u1")),
    "umbrella_concept3": (54, 18, "U3 Piatta: a shallow wide canopy of seven panels.", lambda: canopy(54, 18, 7, 1.6, "u3")),
}


# ------------------------------------------------------------------------------ the waves
def frothy(points, bumps: int, depth: float, seed: str):
    """The upper edge of a foam lip: the polyline ``points`` with ``bumps`` rounded bumps cut
    along it, so the crest is froth rather than a stroke."""
    out = []
    total = len(points) - 1
    for i in range(total):
        (x0, y0), (x1, y1) = points[i], points[i + 1]
        out.append((x0, y0))
        if i % max(1, total // bumps) == 0:
            for t in (0.3, 0.5, 0.7):
                bulge = depth * math.sin(math.pi * t)
                out.append((x0 + (x1 - x0) * t, y0 + (y1 - y0) * t - bulge))
    out.append(points[-1])
    return cut(out, seed, 0.3)


def wave_cavallone(frame: int) -> list[str]:
    """A curling crest: the lip runs up the back of the swell and tips forward, with bubbles
    thrown off the tip. Two frames: the lip and the bubbles move, the crest does not."""
    shift = 0.0 if frame == 0 else 2.5
    top = [(3, 21), (12, 16), (22, 10.5), (33, 6.5), (44, 4.2), (55, 4.6), (64, 7.4), (70, 11.5), (72.5, 16.5)]
    bottom = [(69, 14.5), (63, 10.8), (55, 9.0), (45, 9.2), (35, 11.4), (25, 15.2), (15, 19.6), (7, 23.0)]
    lip = frothy(top, 5 if frame == 0 else 4, 1.6, f"w1-lip-{frame}") + bottom
    shade = [(69, 14.5), (63, 10.8), (55, 9.0), (45, 9.2), (35, 11.4), (25, 15.2), (15, 19.6), (7, 23.0),
             (9, 23.6), (17, 20.8), (27, 16.8), (37, 13.2), (46, 11.2), (55, 11.0), (62, 12.6), (67.5, 15.8)]
    bubbles = [circle_pts(75.5 + shift, 9.5, 2.4, 10), circle_pts(79.0 + shift * 0.6, 14.5, 1.8, 10),
               circle_pts(61.0 + shift, 2.6, 1.6, 10)]
    out = [poly(cut(shade, f"w1-shade-{frame}", 0.3), PAPER_3), poly(lip, WHITE)]
    out += [poly(cut(b, f"w1-bubble-{i}-{frame}", 0.2), PAPER_1) for i, b in enumerate(bubbles)]
    return out


def wave_cresta_doppia() -> list[str]:
    out = []
    for i, (x0, x1, y) in enumerate([(4, 46, 9.0), (52, 92, 7.0)]):
        top = [(x0, y + 6), (x0 + 8, y + 2), ((x0 + x1) / 2, y - 3), (x1 - 8, y + 1), (x1, y + 5)]
        bottom = [(x1 - 4, y + 8.4), ((x0 + x1) / 2, y + 6.4), (x0 + 4, y + 9.0)]
        lip = frothy(top, 4, 1.4, f"w2-lip-{i}") + bottom
        shade = bottom[::-1] + [(x0 + 6, y + 10.6), ((x0 + x1) / 2, y + 8.6), (x1 - 6, y + 10.2)]
        out.append(poly(cut(shade, f"w2-shade-{i}", 0.3), PAPER_3))
        out.append(poly(lip, WHITE))
    return out


def wave_increspatura() -> list[str]:
    top = [(2, 9), (8, 5), (14, 2.8), (20, 4.4), (26, 2.6), (33, 6.5)]
    bottom = [(30, 8.6), (24, 6.8), (18, 8.4), (12, 7.6), (6, 10.6)]
    lip = frothy(top, 3, 1.2, "w3-lip") + bottom
    shade = bottom[::-1] + [(8, 11.8), (14, 9.4), (19, 10.4), (25, 8.6), (31, 10.2)]
    return [poly(cut(shade, "w3-shade", 0.25), PAPER_3), poly(lip, WHITE)]


WAVES = {
    "wave_concept1_frame0": (84, 24, "W1 Cavallone, frame 0.", lambda: wave_cavallone(0)),
    "wave_concept1_frame1": (84, 24, "W1 Cavallone, frame 1.", lambda: wave_cavallone(1)),
    "wave_concept2": (96, 18, "W2 Cresta doppia.", wave_cresta_doppia),
    "wave_concept3": (36, 12, "W3 Increspature.", wave_increspatura),
}


# ------------------------------------------------------------------------------ the waves, round 2
# Round 1 (W1-W3) failed at 1x: small thin foam marks. Round 2 is few and large, with a BODY --
# a crest of foam over a dark face -- or a motion. Every sprite is a tintable mask: a *body* mask
# is tinted with the water carried toward black, a *foam* mask with the water carried toward white.
def mound(pts_top, x0, x1, base_y, seed):
    """A wave body: the top outline ``pts_top`` from left to right, closed along ``base_y``."""
    return cut([(x0, base_y)] + list(pts_top) + [(x1, base_y)], seed, 0.4)


def lip(top_pts, under_pts, bumps, depth, seed):
    """A foam lip: a frothy upper edge over ``top_pts`` and a plain lower edge back along
    ``under_pts`` (given left to right, reversed here)."""
    return frothy(top_pts, bumps, depth, seed + "-top") + list(reversed(under_pts))


def wave_a() -> dict:
    """WA "Cavallone con corpo", 132x36 units: one big breaker leaning into +x, a dark face under
    a thick foam crest, bubbles thrown off the tip."""
    body = mound([(6, 33), (22, 26), (40, 16), (58, 8), (74, 3.5), (88, 5), (98, 10), (106, 18), (112, 27), (116, 35)], 4, 118, 36, "wa-body")
    crest = lip([(44, 14), (54, 8), (66, 3), (78, 1), (90, 3), (100, 8), (106, 14)],
                [(48, 18), (56, 13), (66, 9), (78, 8), (90, 10), (99, 14), (104, 19)], 5, 2.2, "wa-lip")
    bubbles = [circle_pts(114, 9, 2.8, 10), circle_pts(121, 15, 2.2, 10), circle_pts(108, 3, 1.8, 10), circle_pts(126, 8, 1.6, 8)]
    return {"wave_a_body": (132, 36, [poly(body, WHITE)]),
            "wave_a_crest": (132, 36, [poly(crest, WHITE)] + [poly(cut(b, f"wa-b{i}", 0.2), PAPER_1) for i, b in enumerate(bubbles)])}


def wave_b() -> dict:
    """WB "Frangenti sulla riva", 120x20 units, three frames of surf arriving along the shore:
    a thin line, the full swell, and the foam breaking up."""
    out = {}
    f0 = lip([(6, 15), (30, 12.5), (60, 11.5), (90, 12.5), (114, 15)], [(8, 18), (30, 17.5), (60, 17), (90, 17.5), (112, 18)], 4, 1.2, "wb-0")
    out["wave_b_foam0"] = (120, 20, [poly(f0, WHITE)])
    f1 = lip([(3, 16), (14, 9), (34, 5), (60, 3.5), (86, 5), (106, 9), (117, 16)], [(6, 19), (20, 18), (60, 17.5), (100, 18), (114, 19)], 6, 2.0, "wb-1")
    out["wave_b_foam1"] = (120, 20, [poly(cut(mound([(10, 12), (34, 7), (60, 5.5), (86, 7), (110, 12)], 4, 116, 20, "wb-1m"), "wb-1m2", 0.2), PAPER_3), poly(f1, WHITE)])
    blobs = [(12, 15, 9, 3.2), (32, 13, 11, 3.6), (56, 12, 12, 4), (80, 13, 11, 3.6), (102, 15, 9, 3.2)]
    parts = [poly(cut(ellipse_arc(cx, cy, rx, ry, 0, 2 * math.pi, 12)[:-1], f"wb-2-{i}", 0.3), WHITE) for i, (cx, cy, rx, ry) in enumerate(blobs)]
    parts += [poly(circle_pts(x, y, r, 8), PAPER_1) for x, y, r in ((22, 8, 1.6), (44, 7, 1.8), (68, 6, 1.6), (92, 8, 1.8))]
    out["wave_b_foam2"] = (120, 20, parts)
    return out


def wave_c() -> dict:
    """WC "Onda che frange", 108x36 units, three frames: the swell rises, breaks, collapses."""
    out = {}
    # 0 rise: a low mound, a thin bright edge on its crest
    out["wave_c_body0"] = (108, 36, [poly(mound([(10, 32), (30, 26), (54, 22), (78, 26), (98, 32)], 6, 102, 36, "wc-b0"), WHITE)])
    out["wave_c_crest0"] = (108, 36, [poly(lip([(34, 24), (54, 21), (74, 24)], [(36, 26.5), (54, 24), (72, 26.5)], 2, 1.0, "wc-c0"), WHITE)])
    # 1 break: tall, the crest curling forward, a big lip
    out["wave_c_body1"] = (108, 36, [poly(mound([(8, 33), (20, 24), (34, 13), (50, 5), (64, 2.5), (76, 4), (84, 9), (90, 17), (94, 26), (96, 35)], 6, 100, 36, "wc-b1"), WHITE)])
    out["wave_c_crest1"] = (108, 36, [poly(lip([(36, 12), (48, 6), (62, 1.5), (74, 2), (84, 7), (90, 13)], [(40, 16), (50, 11), (62, 7.5), (74, 7), (82, 11), (87, 16)], 5, 2.2, "wc-c1"), WHITE),
                                      poly(circle_pts(98, 8, 2.4, 10), PAPER_1), poly(circle_pts(103, 14, 1.8, 8), PAPER_1)])
    # 2 collapse: a wide flat mound under a spread of foam and bubbles
    out["wave_c_body2"] = (108, 36, [poly(mound([(4, 33), (24, 28), (54, 25), (84, 28), (104, 33)], 2, 106, 36, "wc-b2"), WHITE)])
    blobs = [(18, 30, 10, 3.4), (40, 27, 13, 4.2), (64, 26, 14, 4.4), (88, 29, 11, 3.6)]
    parts = [poly(cut(ellipse_arc(cx, cy, rx, ry, 0, 2 * math.pi, 12)[:-1], f"wc-2-{i}", 0.3), WHITE) for i, (cx, cy, rx, ry) in enumerate(blobs)]
    parts += [poly(circle_pts(x, y, r, 8), PAPER_1) for x, y, r in ((30, 20, 1.8), (52, 18, 2.0), (76, 19, 1.8), (98, 22, 1.5))]
    out["wave_c_crest2"] = (108, 36, parts)
    return out


def wave_a1() -> dict:
    """WA1 "Cresta che sporge", 140x40 units: a long low back slope on the left, a steep face on
    the right, and a crest lip that overhangs the face by a good ten units, with a streak of foam
    trailing back down the slope. The overhang is what says the direction."""
    body = mound([(6, 37), (24, 32), (44, 26), (64, 18), (82, 10), (96, 5), (106, 4), (112, 8), (116, 16), (118, 26), (119, 38)], 4, 121, 40, "wa1-body")
    crest = lip([(78, 15), (88, 8), (98, 3), (108, 1.5), (120, 3), (130, 7), (136, 12)],
                [(82, 19), (90, 13), (98, 9), (108, 8), (118, 9), (126, 12), (132, 17)], 5, 2.2, "wa1-lip")
    streak = cut([(18, 33), (40, 27), (62, 20), (78, 14), (80, 17), (64, 24), (42, 31), (20, 36)], "wa1-streak", 0.3)
    spray = [circle_pts(134, 20, 2.2, 10), circle_pts(139, 15, 1.6, 8), circle_pts(128, 24, 1.4, 8)]
    return {"wave_a1_body": (140, 40, [poly(body, WHITE)]),
            "wave_a1_crest": (140, 40, [poly(streak, PAPER_2), poly(crest, WHITE)] + [poly(cut(b, f"wa1-s{i}", 0.2), PAPER_1) for i, b in enumerate(spray)])}


def wave_a2() -> dict:
    """WA2 "Rullo lungo", 150x30 units: a long, low roller whose whole front-top edge carries a
    foam line, the face steep along its length, a short back and a small spray at the head."""
    body = mound([(4, 28), (20, 22), (44, 15), (74, 9), (104, 6), (126, 6), (136, 9), (142, 15), (145, 22), (146, 29)], 3, 147, 30, "wa2-body")
    crest = lip([(30, 16), (50, 10), (74, 5.5), (100, 3), (124, 2.5), (138, 5), (144, 10)],
                [(34, 19), (52, 14), (76, 10), (100, 8), (124, 7.5), (136, 9), (141, 13)], 7, 1.8, "wa2-lip")
    spray = [circle_pts(146, 4, 1.8, 8), circle_pts(149, 9, 1.4, 8)]
    return {"wave_a2_body": (150, 30, [poly(body, WHITE)]),
            "wave_a2_crest": (150, 30, [poly(crest, WHITE)] + [poly(cut(b, f"wa2-s{i}", 0.2), PAPER_1) for i, b in enumerate(spray)])}


def wave_a3() -> dict:
    """WA3 "Tubo", 120x44 units: short and tall, the crest hooks over into a tube with a hollow
    under the lip (a notch cut out of the body), spray thrown forward off the tip."""
    body = cut([(4, 42), (16, 36), (30, 26), (44, 14), (58, 6), (72, 3), (84, 4), (92, 9), (96, 16),
                (92, 20), (84, 18), (78, 22), (84, 30), (94, 36), (100, 43)], "wa3-body", 0.4)
    crest = lip([(50, 14), (60, 7), (72, 2.5), (86, 2), (98, 6), (106, 13), (108, 20)],
                [(54, 18), (62, 12), (72, 8), (86, 7.5), (96, 11), (101, 16), (102, 21)], 5, 2.2, "wa3-lip")
    spray = [circle_pts(110, 26, 2.6, 10), circle_pts(115, 20, 2.0, 8), circle_pts(112, 33, 1.8, 8), circle_pts(118, 29, 1.4, 8)]
    return {"wave_a3_body": (120, 44, [poly(body, WHITE)]),
            "wave_a3_crest": (120, 44, [poly(crest, WHITE)] + [poly(cut(b, f"wa3-s{i}", 0.2), PAPER_1) for i, b in enumerate(spray)])}


WAVES3 = {}
for _fn in (wave_a1, wave_a2, wave_a3):
    WAVES3.update(_fn())


WAVES2 = {}
for _fn in (wave_a, wave_b, wave_c):
    WAVES2.update(_fn())


# ------------------------------------------------------------------------------ build
def tint_stats(pixels) -> tuple[float, int]:
    import numpy as np
    a = np.asarray(pixels)
    opaque = a[..., 3] > 0
    return float(a[..., 0][opaque].mean()), int(a[..., 0][opaque].min())


def emit(family: str, name: str, svg: str, expected: tuple[int, int], scale: str, note: str, entries: list) -> None:
    out = HERE / family
    out.mkdir(parents=True, exist_ok=True)
    (out / f"{name}.svg").write_text(svg + "\n", encoding="utf-8")
    r = raster.render_svg(svg)
    if r.size != expected:
        raise SystemExit(f"{name}: rendered {r.size}, expected {expected}")
    (out / f"{name}.png").write_bytes(r.png_bytes)
    m = measure_raster(name, r)
    mean, mn = tint_stats(r.pixels)
    ok = "ok" if (mean >= 220 and mn >= 219) else "FAILS TINT CLASS"
    print(f"  {family:9s} {name:22s} {expected[0]}x{expected[1]} content {list(m.content_bbox)} "
          f"tint mean {mean:.1f} min {mn} {ok}  decoded {expected[0] * expected[1] * 4} B")
    entries.append({"name": name, "category": family, "width": expected[0], "height": expected[1],
                    "contentBox": list(m.content_bbox), "scale": scale, "tint": "TINTABLE", "usage": "concept",
                    "anchorRule": "PART_LOCAL", "anchor": [0, 0], "season": "all",
                    "source": {"kind": "svg", "file": f"{name}.svg"}, "notes": note})


def build() -> None:
    for family, table in (("bird", BIRDS), ("umbrella", UMBRELLAS), ("wave", WAVES), ("wave2", WAVES2), ("wave3", WAVES3)):
        entries: list = []
        for name, spec in table.items():
            if family == "bird":
                note, fn = spec
                svg = svg_doc(BIRD_W, BIRD_H, BIRD_W, BIRD_H, f"v4.28 bird concept: {note} Flap axis row {AXIS:g}.", fn())
                emit(family, name, svg, (BIRD_W, BIRD_H), "CANVAS_PIXELS", note + f" 51x21 CANVAS_PIXELS, flap axis row {AXIS:g}, blit origin (-25, -15).", entries)
            elif family in ("wave2", "wave3"):
                w, h, parts = spec
                svg = svg_doc(w * UNIT, h * UNIT, w, h, f"v4.28 wave concept, round 2: {name}.", parts)
                emit(family, name, svg, (w * UNIT, h * UNIT), "SCENE_UNITS", f"Round-2 wave concept {name}: {w}x{h} units, SCENE_UNITS, tintable mask (body masks tinted dark, foam masks tinted light).", entries)
                continue
            else:
                w, h, note, fn = spec
                svg = svg_doc(w * UNIT, h * UNIT, w, h, f"v4.28 {family} concept: {note}", fn())
                emit(family, name, svg, (w * UNIT, h * UNIT), "SCENE_UNITS", note + f" {w}x{h} units, SCENE_UNITS, tintable mask.", entries)
        reg = {"schemaVersion": 2, "note": f"v4.28 phase-1 {family} concepts; NOT shipped.", "sprites": entries}
        (HERE / family / "sprites.concept.json").write_text(json.dumps(reg, indent=1) + "\n", encoding="utf-8")


if __name__ == "__main__":
    build()
